name: Test
version: '1.0'
main: me.rr.test.PriniumAtmosphere
api-version: '1.20'
load: STARTUP
authors: [Richard Rainhardt]

commands:
  giveoxygengenerator:
    description: Выдает генератор атмосферы
    usage: /giveoxygengenerator
    permission: ap.give.oxygen
  givegravigenerator:
    description: Выдает генератор гравитации
    usage: /givegravigenerator
    permission: ap.give.gravigen